[package]
name = "rikai"
version = "0.1.0"
authors = ["esehara shigeo <esehara@gmail.com>"]
edition = "2018"

[dependencies]
scraper="0.12.0"
structopt="0.3.13"
tera="1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"